info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-04-02T08:39:58.186Z"}
info: Connected to the database. {"timestamp":"2022-04-02T08:39:58.208Z"}
error: 
    status - 500 
    message - BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters
    at new BSONTypeError (C:\Projects\EmpType\node_modules\mongodb\node_modules\bson\src\error.ts:16:5)
    at new ObjectId (C:\Projects\EmpType\node_modules\mongodb\node_modules\bson\src\objectid.ts:86:15)
    at UserDao.<anonymous> (C:\Projects\EmpType\src\Dao\user.dao.ts:35:83)
    at Generator.next (<anonymous>)
    at C:\Projects\EmpType\src\Dao\user.dao.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Projects\EmpType\src\Dao\user.dao.ts:4:12)
    at UserDao.deleteUser (C:\Projects\EmpType\src\Dao\user.dao.ts:34:47)
    at UserService.<anonymous> (C:\Projects\EmpType\src\services\UserService.ts:40:31)
    at Generator.next (<anonymous>) 
    url - /api/v1/users/undefined 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-04-02T16:43:19.577Z"}
error: 
    status - 500 
    message - BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters
    at new BSONTypeError (C:\Projects\EmpType\node_modules\mongodb\node_modules\bson\src\error.ts:16:5)
    at new ObjectId (C:\Projects\EmpType\node_modules\mongodb\node_modules\bson\src\objectid.ts:86:15)
    at UserDao.<anonymous> (C:\Projects\EmpType\src\Dao\user.dao.ts:35:83)
    at Generator.next (<anonymous>)
    at C:\Projects\EmpType\src\Dao\user.dao.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Projects\EmpType\src\Dao\user.dao.ts:4:12)
    at UserDao.deleteUser (C:\Projects\EmpType\src\Dao\user.dao.ts:34:47)
    at UserService.<anonymous> (C:\Projects\EmpType\src\services\UserService.ts:40:31)
    at Generator.next (<anonymous>) 
    url - /api/v1/users/[object%20Object] 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-04-02T17:15:17.716Z"}
error: 
      status - 66
      message - Plan executor error during findAndModify :: caused by :: Performing an update on the path '_id' would modify the immutable field '_id' 
      url - /api/v1/users/62488675a9c28f5fbb8642dd 
      method - PUT 
      IP - ::1
     {"timestamp":"2022-04-02T17:47:41.266Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 66
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (C:\Projects\EmpType\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Projects\EmpType\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Projects\EmpType\node_modules\express\lib\response.js:267:15)
    at ErrorMiddleware.appErrorHandler (C:\Projects\EmpType\src\middlewares\ErrorMiddleware.ts:53:28)
    at Layer.handle_error (C:\Projects\EmpType\node_modules\express\lib\router\layer.js:71:5) 
    url - /api/v1/users/62488675a9c28f5fbb8642dd 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-04-02T17:47:41.273Z"}
error: 
      status - 66
      message - Plan executor error during findAndModify :: caused by :: Performing an update on the path '_id' would modify the immutable field '_id' 
      url - /api/v1/users/62488675a9c28f5fbb8642dd 
      method - PUT 
      IP - ::1
     {"timestamp":"2022-04-02T17:48:43.480Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 66
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (C:\Projects\EmpType\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Projects\EmpType\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Projects\EmpType\node_modules\express\lib\response.js:267:15)
    at ErrorMiddleware.appErrorHandler (C:\Projects\EmpType\src\middlewares\ErrorMiddleware.ts:53:28)
    at Layer.handle_error (C:\Projects\EmpType\node_modules\express\lib\router\layer.js:71:5) 
    url - /api/v1/users/62488675a9c28f5fbb8642dd 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-04-02T17:48:43.515Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-04-02T18:07:26.927Z"}
info: Connected to the database. {"timestamp":"2022-04-02T18:07:26.946Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-04-02T18:13:02.889Z"}
info: Connected to the database. {"timestamp":"2022-04-02T18:13:02.910Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-04-02T18:17:26.124Z"}
info: Connected to the database. {"timestamp":"2022-04-02T18:17:26.147Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-04-02T18:17:41.000Z"}
info: Connected to the database. {"timestamp":"2022-04-02T18:17:41.022Z"}
error: 
      status - 66
      message - Plan executor error during findAndModify :: caused by :: Performing an update on the path '_id' would modify the immutable field '_id' 
      url - /api/v1/emps/62488675a9c28f5fbb8642dd 
      method - PUT 
      IP - ::1
     {"timestamp":"2022-04-02T18:19:38.710Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 66
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (C:\Projects\EmpType\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Projects\EmpType\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Projects\EmpType\node_modules\express\lib\response.js:267:15)
    at ErrorMiddleware.appErrorHandler (C:\Projects\EmpType\src\middlewares\ErrorMiddleware.ts:53:28)
    at Layer.handle_error (C:\Projects\EmpType\node_modules\express\lib\router\layer.js:71:5) 
    url - /api/v1/emps/62488675a9c28f5fbb8642dd 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-04-02T18:19:38.734Z"}
